[package]
name = "delver"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
indexmap = "2.2.3"
log = "0.4.22"
lopdf = { version = "0.34.0", features = ["nom_parser", "serde"] }
nom = "7.1.3"
pest = "2.7.14"
pest_derive = "2.7.14"
rayon = "1.10.0"
regex = "1.11.0"
serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.132"
shellexpand = "3.1.0"
strsim = "0.11.1"
tokenizers = "0.20.3"
tokio = "1.41.0"
unicode-normalization = "0.1.24"
